"""empty message

Revision ID: 32435eaa6d13
Revises: d00a1cf9f59f
Create Date: 2023-04-17 15:30:23.728439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32435eaa6d13'
down_revision = 'd00a1cf9f59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_memorized', sa.Integer(), nullable=False, server_default='1', onupdate='1'))
        batch_op.add_column(sa.Column('last_recite', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text', schema=None) as batch_op:
        batch_op.drop_column('last_recite')
        batch_op.drop_column('level_memorized')

    # ### end Alembic commands ###
